### ISSUE TITLE
Gradle Build Failed

### ISSUE THREAD

**Issue by aavash1** [crillab/jkahypar#2]
I have been following the steps mentioned in the Readme file to build the library in Linux OS. Building this library requires Boost 1.73 and Gradle and my current java version is 1.8.0_202. However, I try to build the Gradle file located in the source folder and run this command `gradle dist` or `gradle jar` I keep on getting the following error. I am new to Gradle project and I am in desperate need to run the graph partitioning tool for my research work. Please look on to this error and suggest me the correct procedure
![gradleerr1](https://user-images.githubusercontent.com/23627253/142797602-8f7de52e-0fb4-4a80-b6da-829acc9abc09.png)
![gradlerr2](https://user-images.githubusercontent.com/23627253/142797607-0fe86ae5-cdc0-44d6-8c99-5a406d93d310.png)
![gradlerr3](https://user-images.githubusercontent.com/23627253/142797608-0af77ce4-5a4c-4894-83f3-092bc9c7203a.png)

**Comment by SebastianSchlag** [comment]
@romainwallon Could you take a look at this, please? @aavash1 already reached out to us via email, but we were unable to help.

**Comment by romainwallon** [comment]
Hi,
The problem comes from the fact that JKaHyPar has been developed in Java 11.
I thought it was specified in the README, but it seems I forgot to add this requirement.

The compilation error you got is related to the fact that JKaHyPar uses Java modules, that were introduced in Java 9.
Because of this, and of several features used in the source code, the library is not expected to compile using versions of Java prior to Java 11.

Is it possible for you to update your version of Java?

**Comment by aavash1** [comment]
@SebastianSchlag Thank you for your help.
@romainwallon I upgraded java to Java SE 11 and the build was successful. Now, there is a "dist" folder in the source which contains "jkahypar-0.2.0.jar". One small step is completed. Thank you
