### ISSUE TITLE
Datatype issue with the hyperedge weight, cannot input DOUBLE value.

### ISSUE THREAD

**Issue by aavash1** [crillab/jkahypar#3]
Why does jkahypar take only integer type for hyperedge weight?
I checked the source and found out that it is designed to handle the weights with integer type value only.
I tried to change the code and rebuild it again with double type for hyperedge weight, however, I get one failure in the class "TestHypergraphPartitioning.java" during the testing phase. It is the "incorrect partitioning issue", as I was debugging the partition that the code creates is something like this [0 1 0 1 0 0 1], whereas the correct solutions are either [0 0 1 0 0 1 1] or [1 1 01 1 0 0].
Thus during the **_assertTrue()_** method, the comparison fails. I will add the screenshot along
![error](https://user-images.githubusercontent.com/23627253/145160418-80437be4-312c-4f9a-9567-eaa62a1720c1.png)
The previous input dataset: 
7 4
1 1 3
1000 1 2 4 5
1 4 5 7
1000 3 6 7

The dataset with double value for hyperedge weight "This is after what I changed with reverse-engineering on the source code"
7 4
1.0 1 3
1000.0 1 2 4 5
1.0 4 5 7
1000.0 3 6 7

Is this because I tried to change the datatype for hyperedge weights?
Previously, after changing the datatype in the entire code hierarchy, I was getting failures during the build process, but then I managed to fix all other issues except this one.
Maybe I have to do something on the config file, thinking this I changed the **heavy_edge** to **random_matching** in **c-rating-store and i-c-rating score** and realized that the build works. But I later realized that even after removing the types of matching from the configuration files, it builds without error. Hence, I assured myself that it has nothing to do with the configuration files.
Is there any other way that I can use the double value for hyperedge weight, without tampering with the code?
And is there any guide or tutorial regarding the configuration file or using the jkahypar?

**Comment by romainwallon** [comment]
Hi @aavash1,

I answer below to your different questions and remarks.

> Why does jkahypar take only integer type for hyperedge weight?

JKaHyPar is based on [KaHyPar](https://github.com/kahypar/kahypar).
More specifically, it is a Java binding of this library: hypergraph partitioning is thus **not** implemented by JKaHyPar.
Instead, all data structures are passed to this native library using JNI/JNA, and is thus highly dependent on KaHyPar's API.
As you can find [here](https://github.com/kahypar/kahypar/blob/500747cf81a6b39c9e3d0a933bc9994e3d86c0db/include/libkahypar.h#L54), weights in KaHyPar are represented as integers, and so does JKaHyPar. 
I may have missed something, but I don't think KaHyPar provides any way to deal with floating point weights.
If you think I am wrong on this, please let me know.

> I tried to change the code and rebuild it again with double type for hyperedge weight, however, I get one failure in the class "TestHypergraphPartitioning.java" during the testing phase.

Because the Java data structures are passed to the KaHyPar native library, these data structures must be compatible with its API.
If you just changed the code in JKaHyPar (and not the C/C++ code of KaHyPar), then the compatibility with KaHyPar is broken: the double values are incorrectly interpreted as integers by the native code (note that the values **are not casted**, but wrongly decoded by the native code).
I guess this is why you get wrong results in the tests.

> Is there any other way that I can use the double value for hyperedge weight, without tampering with the code?

Currently, I don't see how you can deal with such values using JKaHyPar, unless you can switch to integers.

> And is there any guide or tutorial regarding the configuration file or using the jkahypar?

For using JKaHyPar as a library, the only documentation we have is the README, which should describe every available feature.
For anything related to the configuration file or for insights regarding how the hypergraph partitioning algorithm works, you should probably look at [KaHyPar's documentation](https://kahypar.org), as all this part is not implemented in JKaHyPar.

**Comment by aavash1** [comment]
@romainwallon I think I have no other option rather than to use the partition based on an unweighted graph. Thank you for your explanation, the confusion has been cleared now.
