### ISSUE TITLE
Cannot invoke "fr.univartois.cril.jkahypar.hypergraph.HypergraphBuilder.build()" because "this.builder" is null ?

### ISSUE THREAD

**Issue by rbelew** [crillab/jkahypar#5]
Note, I'm using this library via clojure's java inter-operability.  so my syntax will be Lisp-ish( :

point `tf` to a metis graph file, then:

```
(def hgp (HypergraphParser. tf))
(type hgp)
=> fr.univartois.cril.jkahypar.tools.HypergraphParser

```
but then:

```
(def hg (.getHypergraph hgp))
Execution error (NullPointerException) at fr.univartois.cril.jkahypar.tools.HypergraphParser/getHypergraph (HypergraphParser.java:225).
Cannot invoke "fr.univartois.cril.jkahypar.hypergraph.HypergraphBuilder.build()" because "this.builder" is null

```
I had thought the builder would be part of the JAR?

**Comment by romainwallon** [comment]
I think you forgot to invoke the `parse()` method of the parser before invoking `getHypergraph()`.

**Comment by rbelew** [comment]
thanks @romainwallon ! and apologies, it seems I missed that critical step.

when I do that, i still get an error:
```
(.parse hgp)
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: ""
```
but it seems to have done the parse nevertheless:
```
(def hg (.getHypergraph hgp))
=> #'hpclj.core/hg
(.getNumberOfVertices hg)
=> 7462
(.getNumberOfHyperedges hg)
=> 2395
```

**Comment by romainwallon** [comment]
Actually, I guess the hypergraph you get after the exception is thrown is incomplete, and not all vertices and hyperedges are present (the numbers you get are those declared in the file, not the one that are actually in the hypergraph).

I think your input file may be syntactically incorrect.
Can you check that it is correct?

If you are not sure, you may also attach it to this issue so that I can have a look.

**Comment by rbelew** [comment]
closed; working on rebuilding from source, cf https://github.com/crillab/jkahypar/issues/6
